services:
  socks5:
    image: ghcr.io/rezzorix/simplesocks5:latest
    container_name: socks5
    restart: unless-stopped
    ports:
      - "1080:1080"
    environment:
      PROXY_USER: yourusername
      PROXY_PASSWORD: yourpassword
