services:
  simplesocks5:
    image: ghcr.io/rezzorix/simplesocks5:latest
    container_name: simplesocks5
    ports:
      - "1080:1080"
    volumes:
      - ./3proxy.cfg:/etc/3proxy/3proxy.cfg
    restart: unless-stopped
